"""atualizando

Revision ID: abf92e2d22c2
Revises: 6404914933f0
Create Date: 2023-10-29 23:49:00.878822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'abf92e2d22c2'
down_revision = '6404914933f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=120),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
